"""create models

Revision ID: bb5f8dddea13
Revises: 
Create Date: 2022-01-16 21:05:07.256472

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bb5f8dddea13"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("flags", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("flags", sa.BigInteger(), nullable=True),
        sa.Column("banned", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "channel_map",
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("thread_id", sa.BigInteger(), nullable=True),
        sa.Column("channel", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["channel"], ["channels.name"], name="fk_channel_map_channels_name_channel"),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("original_id", sa.BigInteger(), nullable=True),
        sa.Column("flags", sa.BigInteger(), nullable=True),
        sa.Column("channel", sa.String(length=255), nullable=True),
        sa.Column("user", sa.BigInteger(), nullable=True),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("webhook_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["channel"], ["channels.name"], name="fk_messages_channels_name_channel"),
        sa.ForeignKeyConstraint(["user"], ["users.id"], name="fk_messages_users_id_user"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_table("channel_map")
    op.drop_table("users")
    op.drop_table("channels")
    # ### end Alembic commands ###
